fs.copy("test2.lua","disk/test2.lua")
fs.copy("/multiTurtleStartup1.lua", "disk/startup")
fs.copy("/multiTurtleStartup2.lua","disk/turtleStartup")
fs.copy("/recipesInitiation.lua", "disk/recipesInitiation")
fs.copy("/resourceCalculator.lua", "disk/resourceCalculator")
fs.copy("/communication.lua", "disk/communication")
fs.copy("/generalHelpingFunctions.lua", "disk/generalHelpingFunctions")
fs.copy("/itemstacksizesAndMaxCounts.lua", "disk/itemstacksizesAndMaxCounts")
fs.copy("/logger.lua", "disk/logger")
fs.copy("/standardValues.lua", "disk/standardValues")
fs.copy("/build.lua", "disk/build")
fs.copy("/crafting.lua", "disk/crafting")
fs.copy("/mining.lua", "disk/mining")
fs.copy("/moveInBase.lua", "disk/moveInBase")
fs.copy("/movement.lua", "disk/movement")
fs.copy("/recipes.lua", "disk/recipes")
fs.copy("/smelting.lua", "disk/smelting")
fs.copy("/farming.lua", "disk/farming")
fs.copy("/init.lua", "disk/init")
fs.copy("/processCommand.lua","disk/processCommand")