require("movement")
require("init")
require("farming")
require("inventory")
require("logger")
require("chestStorageSystem")
require("crafting")
require("generalHelpingFunctions")
require("itemstacksizesAndMaxCounts")
require("recipes")
require("mining")
require("standardValues")
require("recipesInitiation")
require("resourceCalculator")
require("singleTurtlePrograms")
require("build")
require("smelting")
require("communication")
require("mainPlanner")
start() --chestStorageSystem

